# Generated by Django 5.2 on 2025-04-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherquery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='weather_photos/'),
        ),
    ]
